In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('teet2.xlsx')
df

    이름   학급  국어점수  영어점수  평균   취미
0  김자바  자바반   100    80  90   독서
1  이자바  자바반    90    90  90  NaN
2  박자바  자바반    80   100  90  NaN
3  최캐드  캐드반    70    50  60   요가
4  정캐드  캐드반    60    60  60   축구

In [ ]:
# 결측치 : 데이터 세트에서 누락된 값(비어있는 데이터, NaN)
# 결측치 제거 : 비어있거나 NaN 데이터를 삭제(행 or 열 삭제)
#              비어있거나 NaN 데이터를 특정 데이터로 채워줌
# 시험문제

In [3]:
# 실습 위해 df에 결측치 추가
import numpy as np

df['학급'] = np.nan
df

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구

In [ ]:
# 결측치를 특정 데이터로 채우기

df1 = df.copy()

# fillna 함수는 nan 데이터에 특정 데이터를 채운 결과를 리턴해줌(원본 데이터는 변경사항 없음)
result_df = df1.fillna('임시데이터')

# 결측치가 래워진 데이터프레임
result_df

# df1은 결측치기 남아있음(NaN)
df1

    이름     학급  국어점수  영어점수  평균     취미
0  김자바  임시데이터   100    80  90     독서
1  이자바  임시데이터    90    90  90  임시데이터
2  박자바  임시데이터    80   100  90  임시데이터
3  최캐드  임시데이터    70    50  60     요가
4  정캐드  임시데이터    60    60  60     축구

In [17]:
# 특정 컬럼의 결측치 제거

df1 = df.copy()
#취미 컬럼의 결측치만 특정 데이터로 채우기
df1['취미'].fillna('없음')

# df1을 출력하면 결측치가 남아있음
df

df1['취미'].fillna('없음', inplace=True)
df1

C:\Users\GRS\AppData\Local\Temp\ipykernel_11552\884788065.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1['취미'].fillna('없음', inplace=True)

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구