In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('teet2.xlsx')
df

    이름   학급  국어점수  영어점수  평균   취미
0  김자바  자바반   100    80  90   독서
1  이자바  자바반    90    90  90  NaN
2  박자바  자바반    80   100  90  NaN
3  최캐드  캐드반    70    50  60   요가
4  정캐드  캐드반    60    60  60   축구

In [ ]:
# 결측치 : 데이터 세트에서 누락된 값(비어있는 데이터, NaN)
# 결측치 제거 : 비어있거나 NaN 데이터를 삭제(행 or 열 삭제)
#              비어있거나 NaN 데이터를 특정 데이터로 채워줌
# 시험문제

In [5]:
# 실습 위해 df에 결측치 추가
import numpy as np

df['학급'] = np.nan
df

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구

In [6]:
# 결측치를 특정 데이터로 채우기

df1 = df.copy()

# fillna 함수는 nan 데이터에 특정 데이터를 채운 결과를 리턴해줌(원본 데이터는 변경사항 없음)
result_df = df1.fillna('임시데이터')

# 결측치가 래워진 데이터프레임
result_df

# df1은 결측치기 남아있음(NaN)
df1

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구

In [7]:
# 특정 컬럼의 결측치 제거

df1 = df.copy()
#취미 컬럼의 결측치만 특정 데이터로 채우기
df1['취미'].fillna('없음')

# df1을 출력하면 결측치가 남아있음
df

df1['취미'].fillna('없음', inplace=True)
df1

C:\Users\GRS\AppData\Local\Temp\ipykernel_7024\884788065.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1['취미'].fillna('없음', inplace=True)

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구

In [8]:
df.isnull()

      이름    학급   국어점수   영어점수     평균     취미
0  False  True  False  False  False  False
1  False  True  False  False  False   True
2  False  True  False  False  False   True
3  False  True  False  False  False  False
4  False  True  False  False  False  False

In [9]:
# 결측치 확인하기
df.isnull() #각 데이터를 True, False로 결측치 표현

df[df.isnull().any(axis=1)]

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구

In [10]:
data = {
    '학번': ['2024001', '2024002', '2024003', '2024004', '2024005',
             '2024006', '2024007', '2024008', '2024009', '2024010'],
    '이름': ['김민준', '이서연', '박지호', '최수아', '정우진',
             '강하은', '윤도현', '임지유', '한준서', '오서현'],
    '학과': ['컴퓨터공학', '정보통신', '컴퓨터공학', None, '정보통신',
             '컴퓨터공학', None, '정보통신', '컴퓨터공학', '소프트웨어'],
    '학년': [1, 2, 1, 3, 2, 1, 3, 2, 1, 3],
    '파이썬점수': [85, 92, None, 95, 88, 73, 90, None, 76, 94],
    '자바점수': [90, None, 82, 88, 92, None, 95, 78, 80, 87],
    '출석률': [95.0, 98.0, 85.0, None, 90.0, 78.0, None, 88.0, 82.0, 96.0]
}

In [11]:
# 결측치 확인하기
df.isnull() #각 데이터를 True, False로 결측치 표현

df[df.isnull().any(axis=1)]

    이름  학급  국어점수  영어점수  평균   취미
0  김자바 NaN   100    80  90   독서
1  이자바 NaN    90    90  90  NaN
2  박자바 NaN    80   100  90  NaN
3  최캐드 NaN    70    50  60   요가
4  정캐드 NaN    60    60  60   축구